### PR TITLE
[DRAFT] Add CallsiteInfoAdder class which populates the event dictionary with callsite info

### LINKED ISSUE #378: Add callsite info to event dictionary
I would like to have the following values in the event dictionary (taken from [`logging` module docs](https://docs.python.org/3/library/logging.html#logrecord-attributes)):

Attribute name | Description
-- | --
filename  | Filename portion of pathname.
pathname | Full pathname of the source file where the logging call was issued (if available).
funcName | Name of function containing the logging call.
module | Module (name portion of filename).
process | Process ID (if available).
processName | Process name (if available).
thread | Thread ID (if available).
threadName | Thread name (if available).
lineno | Source line number where the logging call was issued (if available).

These values can be added with custom processors, but it would be nice to add these to structlog to reduce the amount of code that has to be copied around.

If you are open to it, I would like to add the following processor to `structlog`:

```python
class CallsiteParameter(str, enum.Enum):
    FUNC_NAME = "funcName"
    THREAD = "thread"
    THREAD_NAME = "threadName"
    PATHNAME = "pathname"
    FILENAME = "filename"
    LINENO = "lineno"
    MODULE = "module"
    PROCESS = "process"
    PROCESS_NAME = "processName"


call_site_parameters: Set[CallsiteParameter] = set(CallsiteParameter)


def _get_processname() -> str:
    processName = "MainProcess"
    mp: Any = sys.modules.get("multiprocessing")
    if mp is not None:
        # Errors may occur if multiprocessing has not finished loading
        # yet - e.g. if a custom import hook causes third-party code
        # to run when multiprocessing calls import. See issue 8200
        # for an example
        try:
            processName = mp.current_process().name
        except Exception:
            pass
    return processName


class CallsiteInfoAdder:
    __slots__ = ["_parameters", "_active_handlers"]

    _handlers: Dict[CallsiteParameter, Callable[[str, inspect.Traceback], Any]] = {
        CallsiteParameter.FUNC_NAME: lambda module, frame_info: frame_info.function,
        CallsiteParameter.THREAD: lambda module, frame_info: threading.get_ident(),
        CallsiteParameter.THREAD_NAME: lambda module, frame_info: threading.current_thread().name,
        CallsiteParameter.PATHNAME: lambda module, frame_info: frame_info.filename,
        CallsiteParameter.FILENAME: lambda module, frame_info: os.path.basename(
            frame_info.filename
        ),
        CallsiteParameter.LINENO: lambda module, frame_info: frame_info.lineno,
        CallsiteParameter.MODULE: lambda module, frame_info: module,
        CallsiteParameter.PROCESS: lambda module, frame_info: os.getpid(),
        CallsiteParameter.PROCESS_NAME: lambda module, frame_info: _get_processname,
    }

    def __init__(
        self, parameters: Set[CallsiteParameter] = call_site_parameters
    ) -> None:
        self._parameters = parameters
        self._active_handlers: List[
            Tuple[CallsiteParameter, Callable[[str, inspect.Traceback], Any]]
        ] = []
        for parameter in self._parameters:
            self._active_handlers.append((parameter, self._handlers[parameter]))

    def __call__(
        self, logger: logging.Logger, name: str, event_dict: EventDict
    ) -> EventDict:
        record: Optional[logging.LogRecord] = event_dict.get("_record")
        if record is not None:
            for parameter in self._parameters:
                event_dict[parameter.value] = record.__dict__[parameter.value]
        else:
            frame, module = structlog._frames._find_first_app_frame_and_name(
                additional_ignores=[__name__]
            )
            frame_info = inspect.getframeinfo(frame)
            for parameter, handler in self._active_handlers:
                handler(module, frame_info)
                event_dict[parameter.value] = handler(module, frame_info)
        return event_dict
```

Another alternative is a simple non configurable process like this:

```python
def add_callsite_info(
    logger: logging.Logger, method_name: str, event_dict: EventDict
) -> EventDict:
    record: Optional[logging.LogRecord] = event_dict.get("_record")
    if record is not None:
        event_dict["funcName"] = record.funcName
        event_dict["thread"] = record.thread
        event_dict["threadName"] = record.threadName
        event_dict["pathname"] = record.pathname
        event_dict["filename"] = record.filename
        event_dict["lineno"] = record.lineno
        event_dict["module"] = record.module
        event_dict["process"] = record.process
        event_dict["processName"] = record.processName
    else:
        frame, module = structlog._frames._find_first_app_frame_and_name(
            additional_ignores=[__name__]
        )
        frame_info = inspect.getframeinfo(frame)
        event_dict["funcName"] = frame_info.function
        event_dict["thread"] = threading.get_ident()
        event_dict["threadName"] = threading.current_thread().name
        event_dict["pathname"] = frame_info.filename
        event_dict["filename"] = os.path.basename(frame_info.filename)
        event_dict["lineno"] = frame_info.lineno
        event_dict["module"] = module
        event_dict["process"] = os.getpid()
        processName = "MainProcess"
        mp: Any = sys.modules.get("multiprocessing")
        if mp is not None:
            # Errors may occur if multiprocessing has not finished loading
            # yet - e.g. if a custom import hook causes third-party code
            # to run when multiprocessing calls import. See issue 8200
            # for an example
            try:
                processName = mp.current_process().name
            except Exception:
                pass

        event_dict["processName"] = processName

    return event_dict
```

However the result in this case will be very noisy and may include things people do not care for.

### PR DESCRIPTION
**Pull request by aucampia**
# Summary

This PR creates a CallsiteInfoAdder processor which will populate the event dictionary with callsite info:

Attribute name | Description
-- | --
pathname | Full pathname of the source file where the logging call was issued (if available).
filename  | Filename portion of pathname.
module | Module (name portion of filename).
funcName | Name of function containing the logging call.
lineno | Source line number where the logging call was issued (if available).
thread | Thread ID (if available).
threadName | Thread name (if available).
process | Process ID (if available).
processName | Process name (if available).

Fixes #378

# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://github.com/hynek/structlog/blob/main/.github/CONTRIBUTING.md) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.

- [x] Added **tests** for changed code.
- [ ] **New APIs** are added to [`typing_examples.py`](https://github.com/hynek/structlog/blob/main/tests/typing_examples.py).
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [`__init__.py`](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [changelog](https://github.com/hynek/structlog/blob/main/CHANGELOG.rst).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by hynek** [comment]
I like the approach and I have only two concerns:

1. The thread info is probably gonna be wrong in async setups. We can say that's fine, but then we'd have to document it.
2. Similar problem: we probably should allow the user to supply more names for `additional_ignores`?

**Comment by aucampia** [comment]
> I like the approach and I have only two concerns:
> 
> 1. The thread info is probably gonna be wrong in async setups. We can say that's fine, but then we'd have to document it.
> 2. Similar problem: we probably should allow the user to supply more names for `additional_ignores`?

Thanks for the heads up on these, I will do some testing with async to see what is what, and I will allow user control of `additional_ignores` and I think the default in this case is redundant.

**Comment by aucampia** [comment]
deleting this PR as I will create a new one from same branch to work around the branch editing issue.

**Comment by gzmarstone** [comment]
I know its closed, but what about class if available as well...  use case would be to find all of the logging calls in a particular class...  You can check if the first arg is self, if it is then get the __class__  and the __name__ of that?

**Comment by gzmarstone** [comment]
No problem, I just noticed the change with the latest release and it would let me delete the code that I had to implemented to log the stdlib items, but then realized that it was missing the Class which I have, so I couldn't delete all of it yet...  I can just leave that part in my code and if it gets added obsolete it, otherwise no big deal...

**Pull request closed without merging**
