### PR TITLE
tmp_bind cleans up properly after exceptions.

### PR DESCRIPTION
**Pull request by Tinche**

### CODE REVIEW

**Comment by hynek** [comment]
a CHANGELOG.rst entry please in present tense and link to this ticket. :)

(and if you’re so inclined: add the missing tox envs to Travis to make coverage pass :))

**Comment by Tinche** [comment]
Does this look alright?

**Comment by hynek** [comment]
Wonderful thank you. :)

**Comment by allardhoeve** [comment]
Cool! Can you please release a new (minor) version containing this fix?

**Comment by hynek** [comment]
I hope to push 16.0.0 tomorrow.

**Pull request merged**
