### PR TITLE
Deprecate structlog.threadlocal

### LINKED ISSUE #406: structlog.threadlocal should be deprecated
I didn't realize it originally, but [as confirmed by Yury](https://twitter.com/1st1/status/1483807086341406720), contextvars are a higher-level abstraction that includes threadlocal and therefore we should stop maintaining both.

Greenlets appear to be [supported too](https://greenlet.readthedocs.io/en/latest/contextvars.html), so we can effectively stop maintaining/testing that code.

---

I'm afraid of the shitstorm if we removed it, but I would deprecate it, add a fat banner in the docs steering people to contextvars, and simplify our testing matrix.

cc @MarkusH

### PR DESCRIPTION
**Pull request by hynek**
Fixes #406

cc @MarkusH @radix

### CODE REVIEW

**Review by radix — APPROVED** [review]
LGTM. I guess it's time for me to switch :)

**Comment by hynek** [comment]
Thanks Chris, and especially thank you for introducing these APIs! They were a game changer and I use them in all my projects now (via contextvars)!

**Comment by ionelmc** [comment]
Sorry for silly question here: merge_threadlocal is redundant if I already use merge_contextvars right?

**Comment by hynek** [comment]
yes, but they don't work on each other's data.

i.e. merge_contextvars only merges whatever has been bound using bind_contextvars and vice versa

**Pull request merged**
