### PR TITLE
optimize `_find_first_app_frame_and_name`

### PR DESCRIPTION
**Pull request by methane**
# Summary

Skip temporary tuple.

Performance impact is very small. But it makes code simpler.

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!
  - There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
  - This is not a pre-requisite for your your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [x] **New APIs** are added to our typing tests in [`api.py`](https://github.com/hynek/structlog/blob/main/tests/typing/api.py).
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
      - The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
- [x] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by methane** [comment]
Since peformance difference is almost invisible to users, I am not sure this need changelog.

**Comment by hynek** [comment]
Interesting, I could swear it's necessary! Could it be this changed at some point? Maybe 2 → 3?

**Comment by hynek** [comment]
ah wait, found it: #174

I don't think the problem it's solving is gone? We should probably add a comment to it.

**Comment by methane** [comment]
Oh, it's really strange bug.
I am trying to reproduce but I can not yet...

Anyway, list comprehension is faster and efficient than `tuple(genexpr)`. tuple constructor need to build temporary list to know length of genexpr.

```
$ python -m timeit -s 's="abcde"' -- '[c for c in s]'
5000000 loops, best of 5: 76.8 nsec per loop

$ python -m timeit -s 's="abcde"' -- 'tuple(c for c in s)'
1000000 loops, best of 5: 247 nsec per loop
```

**Comment by methane** [comment]
Just for fun:

```py
    while [i for i in ignores if name.startswith(i)]:
```

```
$ .venv/bin/python logging_bench.py # while [i for i in...]
<_FixedFindCallerLogger hello (INFO)>
8.033us
```

This is the fastest one-liner.

**Comment by methane** [comment]
I forgot that str.startswith() takes a tuple. It is simple, fast, and safe.

```
$ .venv/bin/python logging_bench.py
<_FixedFindCallerLogger hello (INFO)>
6.974us
```

**Comment by hynek** [comment]
Nice, thanks!

**Pull request merged**
