### PR TITLE
Fix dev.ConsoleRenderer wrt. key 'event'

### PR DESCRIPTION
**Pull request by ma-ric**
handle the cases if 'event' is missing in event_dict or not a string

### CODE REVIEW

**Comment by ma-ric** [comment]
Locally I only run tests for py36, so I was not aware of the failing test related to py2 and utf string.

Is there a reason that the "event" is never repr'ed, as stated in the test, or could I change the test?

**Comment by ma-ric** [comment]
wrapped "event" inside `str` instead of `self._repr`, so all tests passes

**Comment by hynek** [comment]
Yeah the reason is that ConsoleRenderer is intended to be mainly human-readable and quotes around the event don’t look too nice.

What is your overall use case/intention?

**Comment by ma-ric** [comment]
Yes this aspect I realized already. Therefore I placed `str` around "event". 

The intention to handle non-string events is only for convinces at writing debug messages at development stage.  An intermediate logging processor could make use of non-string "event". 

A use case for a missing "event" could be: ` log.debug(**some_dict)`

**Comment by hynek** [comment]
So I thought about this (way too long admittedly :|) and I’m going to decline it.  ConsoleRenderer is intended to be human-readable and event is supposed to have special meaning.  Your use case can be simply achieved using `log.debug("dump", **somedict)`.

**Pull request closed without merging**
