### PR TITLE
Migrated from `event_loop` fixture

### PR DESCRIPTION
**Pull request by pahrohfit**
While I was mucking with code, came across a coming depreciate from `pytest-asyncio` where they are deprecating using the `event_loop` fixture in favor of the more portable:
```python
        event_loop = asyncio.get_running_loop()
```

Migrated to this [recommended](https://github.com/pytest-dev/pytest-asyncio/issues/638) method.

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!

  There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.

  This is not a pre-requisite for your your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [x] **New APIs** are added to our typing tests in [`api.py`](https://github.com/hynek/structlog/blob/main/tests/typing/api.py).
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).

      The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
- [x] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Review by hynek — CHANGES_REQUESTED** [review]
Thanks!

Please remove those type annotations (they're in typeshed just fine) and we don't need a changelog entry for such an internal change. I'm trying to keep the changelog as a message to our users and our users don't care about our tests. :)

**Comment by pahrohfit** [comment]
> Thanks!
> 
> Please remove those type annotations (they're in typeshed just fine) and we don't need a changelog entry for such an internal change. I'm trying to keep the changelog as a message to our users and our users don't care about our tests. :)

Done!

**Review by hynek — APPROVED** [review]
Perfect, thanks!

**Comment by pahrohfit** [comment]
No problem

**Pull request merged**
