### PR TITLE
Allow to preserve keys order in ConsoleRenderer. Related to #166

### PR DESCRIPTION
**Pull request by darklow**
# Pull Request Check List

This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.structlog.org/en/latest/contributing.html) at least once, it will save you unnecessary review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) are documented in the [changelog](https://github.com/hynek/structlog/blob/main/CHANGELOG.rst).

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by hynek** [comment]
In case you're waiting for feedback:

- the CI is failing
- we don't need OrderedDict since structlog is 3.6+
- it needs a `.. versionadded`
- it needs a changelog entry

**Comment by mje-nz** [comment]
@darklow For what it's worth, I'm also interested in this feature.

**Comment by darklow** [comment]
I personally see lot of value organising keys by priority, most important at first, and more secondary later rather relying on alphabet. Also having same length parameters as first helps readability as well. 

Just pushed three things you mentioned.

**Comment by hynek** [comment]
> I personally see lot of value organising keys by priority, most important at first, and more secondary later rather relying on alphabet.

To be clear, I don't disagree. It's just not always clear that the most important keys are merged first and sorting them gives a stable order which is also useful.

**Review by hynek — APPROVED** [review]
thanks!

**Comment by darklow** [comment]
Thanks for approval and docs fix!

**Pull request merged**
