### PR TITLE
Added `AddCallingClassPath` processor

### PR DESCRIPTION
**Pull request by pahrohfit**
# Summary

Added a `class_path` event entry processor as `AddCallingClassPath` (#386, #492).

Takes an optional `set` or `list` to limit which logging levels to add this at, as lookups potentially can add overhead (though should run in N(1)).

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!

  There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.

  This is not a pre-requisite for your your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [x] **New APIs** are added to our typing tests in [`api.py`](https://github.com/hynek/structlog/blob/main/tests/typing/api.py).
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).

      The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
- [x] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [x] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by pahrohfit** [comment]
Sample code:

`foo/sub_module.py`
```python
import structlog


logger = structlog.get_logger()

async def async_logging(l):
    await logger.ainfo(l)

class SubModuleClassBasedCall:
    def class_sync_logging(l):
        logger.info(l)

    async def class_async_logging(l):
        await logger.adebug(l)
```

`demo.py`
```python
import asyncio
import structlog

from foo import sub_module
from foo.sub_module import SubModuleClassBasedCall

structlog.configure(
    processors=[
        structlog.processors.AddCallingClassPath(levels={}),
        structlog.processors.JSONRenderer(),
    ],
    context_class=dict,
    cache_logger_on_first_use=True,
)
logger = structlog.get_logger()


def sync_logging(l):
    logger.debug(l)


class ClassBasedCall:
    async def class_async_logging(l):
        await logger.adebug(l)


if __name__ == "__main__":
    logger.info("hello from __main__ direct")
    sync_logging("hello from __main__ via function")
    sub_module.SubModuleClassBasedCall.class_sync_logging(
        "hello from sub_module.class sync logging"
    )
    SubModuleClassBasedCall.class_sync_logging(
        "hello from sub_module imported class sync logging"
    )

    loop = asyncio.get_event_loop()
    loop.run_until_complete(
        ClassBasedCall.class_async_logging(
            "hello from __main__ class async logging"
        )
    )
    loop.run_until_complete(
        sub_module.async_logging(
            "hello from sub_module function async logging"
        )
    )
    loop.run_until_complete(
        SubModuleClassBasedCall.class_async_logging(
            "hello from sub_module imported class async logging"
        )
    )
    loop.close()
```

```console
$ python demo.py
{"event": "hello from __main__ direct", "class_path": "__main__.<module>"}
{"event": "hello from __main__ via function", "class_path": "__main__.sync_logging"}
{"event": "hello from sub_module.class sync logging", "class_path": "foo.sub_module.SubModuleClassBasedCall.class_sync_logging"}
{"event": "hello from sub_module imported class sync logging", "class_path": "foo.sub_module.SubModuleClassBasedCall.class_sync_logging"}
{"event": "hello from __main__ class async logging", "class_path": "__main__.ClassBasedCall.class_async_logging"}
{"event": "hello from sub_module function async logging", "class_path": "foo.sub_module.async_logging"}
{"event": "hello from sub_module imported class async logging", "class_path": "foo.sub_module.SubModuleClassBasedCall.class_async_logging"}
```

**Comment by pahrohfit** [comment]
@hynek -- I can't figure out a better way to get around that partial branch failure from the `break` statement. Thoughts on what I'm missing?

**Comment by pahrohfit** [comment]
> @hynek -- I can't figure out a better way to get around that partial branch failure from the `break` statement. Thoughts on what I'm missing?

I moved to a queue for iteration to get rid of the 'break' to make it pass

**Comment by macintacos** [comment]
Just some passing nitpicky feedback - I'm not sure I like "class path", considering that it's not reliant on classes. Probably more accurate to call it a namespace/module path or something like that?

**Comment by pahrohfit** [comment]
> Just some passing nitpicky feedback - I'm not sure I like "class path", considering that it's not reliant on classes. Probably more accurate to call it a namespace/module path or something like that?

Sounds like reasonable feedback -- went based on the body of #386. Namespace seems clearer and more precise to me

**Comment by pahrohfit** [comment]
Branch renamed. Replacement PR #570

**Pull request closed without merging**
