### PR TITLE
Add String Interpolation to FilteringBoundLogger for exceptions.

### PR DESCRIPTION
**Pull request by jriggins**
# Summary

👋🏾 I'm extremely new to this project (as in just trying it out today 😅 ).

I came across this issue as I was playing around with it. Perhaps, I'm doing something wrong? If not, this is my attempt to fix it.

Before my changes:

```python
>>> from structlog import get_logger
>>> logger = get_logger()
>>> logger.exception("boom! code: %i", 42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exception() takes 2 positional arguments but 3 were given
```

After:

```python
>>> from structlog import get_logger
>>> logger = get_logger()
>>> logger.exception("boom! code: %i", 42)
2023-01-07 01:59:28 [error    ] boom! code: 42 
NoneType: None
```
If this looks like I'm on the right track I will complete the doc changes as mentioned in the checklist, but I wanted to get some feedback first if that is alright. Thanks!

# Pull Request Check List

- [x] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [ ] **New APIs** are added to [`typing_examples.py`](https://github.com/hynek/structlog/blob/main/tests/typing_examples.py).
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
      Find the appropriate next version in our [`__init__.py`](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [ ] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by hynek** [comment]
Hi Jesse, any reason you've closed this PR? If it's the long wait: I tend to work in batches on my projects and structlog is a bit on a backburner until I've resolved others. That's no value judgement of anything open here, I just can't focus on so many things at once. If your changes are still valid, please re-open – I'll get to it.

**Comment by jriggins** [comment]
Hi @hynek sorry. I did close without posting a reason. I think my premise may have been wrong as it appears that we expect  `logger.exception` to be issued in the context of an exception. At least when I do that, things seem to work fine. If not, then I may have some additional work to do as the example above in my PR no longer works as expected even though the tests pass.

**Comment by hynek** [comment]
I have just briefly played with `logging`:

```pycon
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.error("foo")
ERROR:root:foo
>>> logging.error("foo %s!", "hi")
ERROR:root:foo hi!
>>> logging.exception("foo %s!", "hi")
ERROR:root:foo hi!
NoneType: None
```

And it looks like pos arg formatting _should_ work!

**Comment by jriggins** [comment]
@hynek Yeah I had thought so as well. I'm happy to revisit this. I had to pause the transition of my project to structlog, but should be back on it soon.

**Pull request closed without merging**
