### PR TITLE
add log() to BoundLoggerFiltering*

### PR DESCRIPTION
**Pull request by FlorianLudwig**
# Summary

add `log()` to `BoundLoggerFiltering*` to better match `BoundLogger` signature 

# Pull Request Check List

- [x] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [?] **New APIs** are added to [`typing_examples.py`](https://github.com/hynek/structlog/blob/main/tests/typing_examples.py) (not actually new, just fixes `stdlib.get_logger().log()`)
- [ ] Updated **documentation** for changed code.
    - [x] I think no documentation update is needed for this addition
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
      Find the appropriate next version in our [`__init__.py`](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [ ] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by hynek** [comment]
When you say BoundLogger, I presume you mean stdlib's one (yes, calling them all same was stupid)?

There's really no guarantee to mirror stdlib APIs in general, do you find that method practically useful and if so how? Because it completely obliterates the performance gains we got by pre-creating concrete classes.

**Comment by FlorianLudwig** [comment]
> When you say BoundLogger, I presume you mean stdlib's one (yes, calling them all same was stupid)?

Indeed. I like using `structlog.stdlib.get_logger` for the type hints.

> There's really no guarantee to mirror stdlib APIs in general, do you find that method practically useful and if so how?

I use it to pipe stdlib logs into structlog.

> Because it completely obliterates the performance gains we got by pre-creating concrete classes.

It should only effect performance for calls that use `.log` but the `.info` etc should be still the same performance, right?

**Comment by hynek** [comment]
OK thanks! I'll fix a few tiny quibbles myself, really weird to document this. 🤔

**Comment by tjb9dc** [comment]
@hynek would you mind cutting a release that has this PR? Thanks!

**Comment by hynek** [comment]
I plan on pushing 22.1 once #407 is merged.

**Pull request merged**
