### PR TITLE
Adds `log()` and `alog()` to `FilteringBoundLogger`.

### LINKED ISSUE #460: FilteringBoundLogger.{log,alog} missing
Hi,

I noticed that the methods `log()` and `alog()` aren't included on `typing.FilteringBoundLogger`.

They are added to the methods of the type here:

https://github.com/hynek/structlog/blob/9509a8c24f82e2ebfa70001b5a4d8f6831c64e7d/src/structlog/_log_levels.py#L193

And there is reference to `alog()` in the docstring:

https://github.com/hynek/structlog/blob/9509a8c24f82e2ebfa70001b5a4d8f6831c64e7d/src/structlog/typing.py#L157

I'd be happy to submit a PR if they are intended to be there.

Thanks!

### PR DESCRIPTION
**Pull request by peterschutt**
Closes #460

# Summary

# Pull Request Check List

- [ ] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [ ] **New APIs** are added to [`typing_examples.py`](https://github.com/hynek/structlog/blob/main/tests/typing_examples.py).
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
      Find the appropriate next version in our [`__init__.py`](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [ ] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [ ] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by peterschutt** [comment]
Happy to improve this if necessary, but I couldn't see any existing tests for the module, and the protocol types are already included in the api docs. LMK, cheers!

**Comment by hynek** [comment]
It would be good if you could add examples of `log()` and `alog()` to typing_examples. That's essentially how we "test" types. Or more precisely: protect against regressions.

**Comment by peterschutt** [comment]
OK, see if that is OK.

I noticed that `amsg()` was missing also.

There is also `err()` defined but I can't see where it is getting created in `_make_filtering_bound_logger()`, should it be there?

**Comment by hynek** [comment]
Thanks!

We don't need `err()` … the only reason I kept `msg()` is because until recently the examples in the docs used it.

**Pull request merged**
