### PR TITLE
Fix exc_info and race condition in ProcessorFormatter

### PR DESCRIPTION
**Pull request by hynek**
Based on / fixes #109 

Hey @andreiko I tried to push it to your branch but I failed at git hard (due to the changes in master) so here’s a new pull request with some changes (and split up of stack_info & exc_info handling).

Does this still fix your problem and do you agree with the approach?

### CODE REVIEW

**Comment by hynek** [comment]
(also @gilbsgilbs  – any opinions?  should be straight-forward, right?)

**Comment by gilbsgilbs** [comment]
Just read it and seems fine and straightforward indeed. I did not test it because I'm away from keyboard (heading to Japan in a minute for 10 days).

I'm 99.99% sure it can't help at any rate in this case, but just to be sure, have a look at `handleError` method somewhere in `logging` (in `Handler` I think).

**Comment by hynek** [comment]
Thank you, enjoy Japan!

**Comment by andreiko** [comment]
This totally fixes my problem. Thank you for fixing the conflicts! Sorry that I wasn't available during the weekend.

**Comment by hynek** [comment]
No problem at all, I’m glad we’ve sorted this out.  17.2 is on PyPI.

**Pull request merged**
