### PR TITLE
Better support for missing __name__ in frame traversal

### PR DESCRIPTION
**Pull request by Callek**
In my own code, I got a new traceback for this issue (meant to be fixed in release of 15.1.0)

With some DEBUG prints sprinkled in, I was able to see that ``f.f_frame.has_key("__name__")`` was ``True``, however ``f.f_frame.get("__name__", "?")`` would still return ``None`` thus skipping that default choice.

Per python docs, ``foo.get("whatever")`` already has a default value of ``None`` so simply mixing them with "or" will achieve the desired goal here in all existing cases, as well as fix my own case.

For reference the full traceback I had:
```
Traceback (most recent call last):
  File "/data/www/relengapi/celery", line 81, in <module>
    load_entry_point('celery', 'console_scripts', 'celery')()
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/worker/__init__.py", line 141, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bootsteps.py", line 209, in apply
    self._debug('Preparing bootsteps.')
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/bootsteps.py", line 272, in _debug
    return debug(_pre(self, msg), *args)
  File "/usr/lib/python2.7/logging/__init__.py", line 1128, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/data/www/relengapi/celery", line 62, in new_log
    old_log(self, level, msg, args, exc_info=None, extra=extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1249, in _log
    fn, lno, func = self.findCaller()
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/structlog/stdlib.py", line 32, in findCaller
    f, name = _find_first_app_frame_and_name(['logging'])
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/structlog/_frames.py", line 41, in _find_first_app_frame_and_name
    while any(name.startswith(i) for i in ignores):
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/structlog/_frames.py", line 41, in <genexpr>
    while any(name.startswith(i) for i in ignores):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

If this patch is accepted, I would appreciate a new structlog release, sooner than later.

### CODE REVIEW

**Comment by Callek** [comment]
See-Also, [Mozilla Bug 1192021] (https://bugzilla.mozilla.org/show_bug.cgi?id=1192021) (comment # 11)

**Comment by hynek** [comment]
Nice edge case, thanks!

I can't release it before next week tho because I'm on a vacation  and I don't have my notebook on me.

You can use the time to add yourself to authors. :)

**Comment by hynek** [comment]
Oh and please add a test case for your exact use case, thanks!

**Comment by Callek** [comment]
How's that?

**Comment by Callek** [comment]
casual nudge. :-)

**Comment by hynek** [comment]
Sorry, first weeks are crazy. :)

**Comment by hynek** [comment]
Oops can you rebase/merge forward please?

**Comment by Callek** [comment]
The conflict is from your py3.5 release notes change... but sure...

**Comment by Callek** [comment]
...merged in master

**Comment by hynek** [comment]
FYI, 15.3.0 with this change is out.  Thank you for your contribution: https://pypi.python.org/pypi/structlog/15.3.0

**Pull request merged**
