### PR TITLE
Add reference to django-structlog

### PR DESCRIPTION
**Pull request by jrobichaud**
I developped a pypi package to easily integrate structlog in django (it also includes a celery integration). I thought it would be helpful to add a reference to it in your documentation.

doc: https://django-structlog.readthedocs.io/en/latest/?badge=latest
pypi: https://pypi.org/project/django-structlog/
github: https://github.com/jrobichaud/django-structlog/

### CODE REVIEW

**Comment by hynek** [comment]
We collect third party extensions at https://github.com/hynek/structlog/wiki/Third-party-Extensions so please add it there. But I'd merge a PR that points users to check the wiki page for django helpers! (the background is that it's simply difficult to keep docs up to date wrt third party projects, so it's better to collect them in one place and let people choose).

**Comment by jrobichaud** [comment]
I changed the url to point to the [Third-party-Extensions](https://github.com/hynek/structlog/wiki/Third-party-Extensions) and I added `django-structlog` to the section.

Is it ok with you?

**Comment by jrobichaud** [comment]
Unless you want something more like:


```
**Django**
	See `Third-party-Extensions <https://github.com/hynek/structlog/wiki/Third-party-Extensions/>`_ in the wiki.
```

**Comment by jrobichaud** [comment]
@hynek I changed the text to refer directly to the wiki. Let me know if there is anything else wrong.

**Comment by jrobichaud** [comment]
Here's a screenshot of the doc I built locally if you want to make sure it rendered correctly.
image

**Comment by hynek** [comment]
Hi Jules, thank you so much for going out of your way to make this simpler for me! And I'm sorry I let you hang for this long with such a simple change.

**Comment by jrobichaud** [comment]
I made [django-structlog](https://www.github.com/jrobichaud/django-structlog/) to make it simpler for django and celery users, I am glad it can help you too.

**Pull request merged**
